#!/usr/bin/env bash
# This script will print "Best School" 9 times then print "Hi" then print "Best School"
i=0
while [ $i -lt 10 ]
      do
	  echo "Best School"
	  
	  if [[ $i = 8 ]]
          do
             echo "Hi"
	  ((i++))
          done
done
