#!/usr/bin/env bash
# This script will print 10 lines of text 8 being "Best School" the 4th one being "bad luck" and the 8th one being "good luck"
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
	echo "bad luck"
    elif [ $i -eq 7 ]
    then
	 echo "good luck"
    else
	echo "Best School"
    fi
	 ((i++))
done
