#!/usr/bin/env bash
# This script will print numbers 1 to 20 except for when the number is a superstitious number in China, Japan, or Italy
i=1
while [ $i -le 20 ]
do
      case $i in

	  4)
	      echo $i
	      echo "bad luck from China"
	      ;;

	  9)
	      echo $i
	      echo "bad luck from Japan"
	      ;;
	  17)
	      echo $i
	      echo "bad luck from Italy"
	      ;;
	  *)
	      echo $i
	      ;;
      esac
      ((i++))
done
