#!/usr/bin/env bash
# This script will display the time for 12 hours and 59 minutes
hour=0
minute=0
while [ $hour -lt 13 ]
do
    case $minute in

	0)
	    echo "Hour: $hour"
	    ((minute++))
	    ;;
	60)
	    minute=0
	    ((hour++))
	    ;;
	*)
	    echo $minute
	    ((minute++))
	    ;;
    esac
done
