#!/usr/bin/env bash
# This script will display the time for 12 hours and 59 minutes
hour=-1
minute=0
while [ $hour -lt 12 ]
do
    case $minute in

	0)
	    echo "Hour: $(( hour + 1 ))"
	    ((hour++))
	    ((minute++))
	    ;;
	60)
	    minute=0
	    ;;
	*)
	    echo $minute
	    ((minute++))
	    ;;
    esac
done
