#!/usr/bin/env bash
# The script will display the content of the current directory in a list format where only the part of the name after the first dash is displayed.
for i in *
do
    echo "$i" | cut -f 2 -d '-'
done
